[phases.setup]
nixPkgs = ["nodejs_18", "pnpm-9_x"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["VITE_API_BASE_URL=https://dropship-hub-production.up.railway.app pnpm run build"]

[start]
cmd = "sh start.sh"
